FROM node:15.14-alpine As builder

WORKDIR /usr/src/app

COPY learnstudio/package.json learnstudio/package-lock.json ./

RUN npm install

COPY learnstudio .

RUN npm run build --prod

FROM nginx:1.15.8-alpine


COPY --from=builder /usr/src/app/dist/learnstudio/ /usr/share/nginx/html
COPY conf/default.conf /etc/nginx/conf.d/default.conf