FROM node:15.14-alpine
RUN mkdir /home/node/app && chown node:node /home/node/app
RUN mkdir /home/node/app/node_modules && chown node:node /home/node/app/node_modules
WORKDIR  /home/node/app
USER node
COPY --chown=node:node learnstudio/package.json learnstudio/package-lock.json ./
RUN npm ci --quiet
COPY --chown=node:node learnstudio .
CMD ["npm", "start"]